language: rust
rust:
   - stable
   - beta
   - nightly
matrix:
   allow_failure:
      - rust: nightly
before_install: |
  sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa &&
  sudo apt-get update -qq &&
  sudo apt-get install qt5-default qtdeclarative5-dev qtdeclarative5-folderlistmodel-plugin qtdeclarative5-qtquick2-plugin cmake
after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/*panopticon-*
