language: rust
rust:
   - stable
   - beta
   - nightly
matrix:
   allow_failure:
      - rust: nightly
addons:
  apt:
    sources:
    - ubuntu-sdk-team
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    packages:
    - cmake
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo apt-add-repository -y ppa:beineri/opt-qt541
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54base qt54declarative qt54quickcontrols kcov libglpk-dev
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      && export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/qt54/lib/pkgconfig/
      && export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/opt/qt54
      ;
    else
         brew update
      && brew install qt5
      && brew install qt5-qmake
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi
after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --exclude-pattern=/.cargo target/kcov target/debug/panopticon-*
  kcov --exclude-pattern=/.cargo target/kcov target/debug/amd64-*
  kcov --exclude-pattern=/.cargo target/kcov target/debug/avr-*
  kcov --exclude-pattern=/.cargo target/kcov target/debug/project-*
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/qtpanopticon-*
script: |
   cargo build --verbose &&
   cargo test --no-run --verbose
