sudo: required
dist: trusty
language: rust
rust:
   - stable
addons:
  apt:
    packages:
    # panopticon
    - cmake
    - qt5-default
    - qtdeclarative5-dev
    - libqt5qml-quickcontrols
    - qtbase5-private-dev
    - pkg-config
    - libglpk-dev
    - git
    - build-essential
    # kcov
    - libelf-dev
    - libcurl4-openssl-dev
    - libbfd-dev
    - libiberty-dev
    - libdw-dev
after_success: |
  # send coverage report to coveralls.io
  wget https://github.com/SimonKagstrom/kcov/archive/v30.tar.gz
  tar xzf v30.tar.gz && mkdir kcov-30/build && cd kcov-30/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  for I in amd64 avr elf panopticon qtpanopticon project
  do
    kcov --verify --include-path=lib,qt target/cov-"$I" target/debug/"$I"-*
  done &&
  kcov --merge --coveralls-id=$TRAVIS_JOB_ID --include-path=lib,qt target/kcov target/cov-*
script: |
   cargo build --verbose &&
   cargo test --verbose
