matrix:
  fast_finish: true
  include:
      # CI targets
      #    - os: osx
      #rust: 1.10.0
      #env: TARGET=x86_64-apple-darwin
      #- os: linux
      #dist: trusty
      #rust: 1.10.0
      #env: TARGET=x86_64-unknown-linux-gnu
      # nightly builds
    - os: linux
      dist: trusty
      rust: 1.10.0
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - PACKAGE=ubuntu
        - secure: "HwY2nRi7xuAQTkuVWgUupdVcJmutiiq+A4iDCbC4NI/vRB7WKCifxlzivCeTJMBu22LSLPJBMoaQ0S7w1PLaPkuG2d0qqFhublmhzk5sLaQt6AiwpEnJaHLqGy6aDVPDbqd4EWlPZ1MMCV+uXhtHzsg9XmrlZH9l5hMGx3mUDJw="
      branches:
        only:
          - master
      #- os: linux
      #dist: trusty
      #rust: 1.10.0
      ##env:
      #  - TARGET=x86_64-unknown-linux-gnu
      #  - PACKAGE=debian
      #branches:
      #  only:
      #    - master
      #- os: osx
      #rust: 1.10.0
      #env:
      #  - TARGET=x86_64-apple-darwin
      #  - PACKAGE=osx
      #branches:
      #  only:
      #    - master

sudo: required
services:
  - docker
notifications:
  irc:
    channels:
      - "chat.freenode.net#panopticon"
    on_success: change
    on_failure: always
language: rust
addons:
  apt:
    packages:
    # panopticon
    - cmake
    - qt5-default
    - qtdeclarative5-dev
    - libqt5qml-quickcontrols # not approved
    - qtbase5-private-dev
    - pkg-config
    - git
    - build-essential
    # kcov
    - libelf-dev
    - libcurl4-openssl-dev
    - libbfd-dev # not approved
    - libiberty-dev # not approved
    - libdw-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/versions/qt55; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux"  && "$PACKAGE" == "" ]]; then sudo apt-get -qq install libbfd-dev libqt5qml-quickcontrols libiberty-dev; fi
after_success: |
  # send coverage report to coveralls.io
  if [[ "$TRAVIS_OS_NAME" == "linux" && "$PACKAGE" == "" ]]; then
      wget https://github.com/SimonKagstrom/kcov/archive/v30.tar.gz
      tar xzf v30.tar.gz && mkdir kcov-30/build && cd kcov-30/build && cmake .. && make &&
      sudo make install && cd ../.. &&
      for I in amd64 avr elf panopticon qtpanopticon project
      do
        kcov --verify --include-path=lib,qt target/cov-"$I" target/debug/"$I"-*
      done &&
      kcov --merge --coveralls-id=$TRAVIS_JOB_ID --include-path=lib,qt target/kcov target/cov-*
  fi
script: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export QTDIR64=`brew --prefix qt55`; fi
  case "$PACKAGE" in
  "osx")
    cd pkg/osx/
    ./package_dmg.sh
    find .
    ;;
  "ubuntu")
    cd pkg/debian
    docker build -t panopticon-build -f Dockerfile.ubuntu .
    docker run -v `pwd`:/out panopticon-build
    find .
    curl -T panopticon_0.15_amd64.deb -u upload:$FTP_PASSWD -v ftp://ftp.panopticon.re/panopticon-master-$TRAVIS_COMMIT.deb
    ;;
  "debian")
    cd pkg/debian
    docker build -t panopticon-build -f Dockerfile.debian .
    docker run -v `pwd`:/out panopticon-build
    find .
    ;;
  "")
    cargo build --verbose &&
    cargo test --verbose
    ;;
  *)
    exit
    ;;
  esac
