language: rust
rust:
   - stable
addons:
  apt:
    sources:
    - ubuntu-sdk-team
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    packages:
    - cmake
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo apt-add-repository -y ppa:beineri/opt-qt542
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54base qt54declarative qt54quickcontrols kcov libglpk-dev
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      && export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/qt54/lib/pkgconfig/
      && export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/opt/qt54
      ;
    else
         brew update
      && brew install qt5
      && brew install qt5-qmake
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi
after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/v30.tar.gz
  tar xzf v30.tar.gz && mkdir kcov-30/build && cd kcov-30/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  for I in amd64 avr elf panopticon qtpanopticon project
  do
    kcov --verify --include-path=lib,qt target/cov-"$I" target/debug/"$I"-*
  done &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --include-path=lib,qt target/kcov target/cov-*
script: |
   cargo build --verbose &&
   cargo test --verbose
