max_width=160
fn_call_width=60
chain_one_line_max=160
reorder_imports=true
reorder_imported_names=true
fn_args_layout = "Block"
array_layout = "Block"
where_style = "Rfc"
generics_indent = "Block"
fn_call_style = "Block"
struct_lit_style = "Block"
struct_lit_multiline_style = "PreferSingle"
struct_lit_width = 60
struct_variant_width = 60
array_width = 80
tab_spaces = 4
use_try_shorthand = true
